<?php
/**
 * @file
 * The Trove module.
 */

define('TROVE_BASE_URL', 'http://api.trove.nla.gov.au/');
define('TROVE_FROM_DATE', '2012-04-04T00:00:00Z');

/**
 * Implements hook_menu().
 */
function trove_menu() {
  $items['admin/config/services/trove'] = array(
    'title' => 'Trove',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trove_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'description' => 'Change settings for the trove module.',
    'file' => 'trove.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function trove_permission() {
  return array(
    'administer torve' => array('title' => t('Administer trove settings')),
  );
}

/**
 * Get the available zones.
 *
 * See @link http://help.nla.gov.au/trove/building-with-trove/api-technical-guide Trove API facets documentation @endlink
 * for detailed facets information.
 *
 * @return array
 *   Array of trove zones.
 */
function trove_get_zones() {
  $zones = array(
    'all',
    'article',
    'book',
    'collection',
    'list',
    'map',
    'music',
    'newspaper',
    'people',
    'picture',
    'website',
  );
  return array_combine($zones, $zones);
}

/**
 * Get the available facet formats.
 *
 * See @link http://help.nla.gov.au/trove/building-with-trove/api-technical-guide#anchor-8 Trove API facets documentation @endlink
 * for detailed facets information.
 *
 * @return array
 *   Array of facets formats.
 */
function trove_get_facets_format() {
  return array(
    'Archived website' => 'Archved website',
    'Art work' => 'Art work',
    'Article' => array(
      'Article/Abstract' => 'Abstract',
      'Article/Book chapter' => 'Book chapter',
      'Article/Conference paper' => 'Conference Paper',
      'Article/Journal or magazne article' => 'Journal or magazine article',
      'Article/Other article' => 'Other article',
      'Article/Report' => 'Report',
      'Article/Review' => 'Review',
      'Article/Working paper' => 'Working paper',
    ),
    'Audio book' => 'Audio book',
    'Book' => array(
      'Book/Braille' => 'Book/Braille',
      'Book/Illustrated' => 'Book/Illustrated',
      'Book/Large print' => 'Book/Large print',
    ),
    'Conference Proceedings' => 'Conference Proceedings',
    'Data set' => 'Data set',
    'Map' => array(
      'Map/Aerial photograph' => 'Aerial photograph',
      'Map/Atlas' => 'Atlas',
      'Map/Braille' => 'Braille',
      'Map/Electronic' => 'Electronic',
      'Map/Globe or object' => 'Globe or object',
      'Map/Large print' => 'Large print',
      'Map/Map series' => 'Map series',
      'Map/Microform' => 'Microform',
      'Map/Single map' => 'Single map',
    ),
    'Object' => 'Object',
    'Periodical' => array(
      'Periodical/Journal, magazine, other' => 'Journal, magazine, other',
      'Periodical/Newspaper' => 'Newspaper',
    ),
    'Photograph' => 'Photograph',
    'Poster, chart, other' => 'Poster, chart, other',
    'Published' => 'Published',
    'Sheet music' => 'Sheet music',
    'Sound' => array(
      'Sound/Interview, lecture, talk' => 'Interview, lecture, talk',
      'Sound/Other sound' => 'Other sound',
      'Sound/Recorded music' => 'Recorded music',
    ),
    'Thesis' => 'Thesis',
    'Unpublished' => 'Unpublished',
    'Video' => array(
      'Video/Captioned' => 'Video/Captioned',
    ),
  );
}

/**
 * Get the availability options.
 *
 * See @link http://help.nla.gov.au/trove/building-with-trove/api-technical-guide#anchor-8 Trove API facets documentation @endlink
 * for detailed facets information.
 *
 * @return array
 *   An array of availability facets
 */
function trove_get_facets_availability() {
  return array(
    'y' => 'online',
    'y/f' => 'freely accessible online',
    'y/r' => 'payment, subscription or membership required',
    'y/s' => 'subscription required',
    'y/u' => 'possibly online',
  );
}

/**
 * Get the category options.
 *
 * See @link http://help.nla.gov.au/trove/building-with-trove/api-technical-guide#anchor-8 Trove API facets documentation @endlink
 * for detailed facets information.
 *
 * @return array
 *   An array of category facets
 */
function trove_get_facets_category() {
  return array(
    'Article' => 'Article',
    'Advertising' => 'Advertising',
    'Details lists, results, guides' => 'Details lists, results, guides',
    'Family notices' => 'Family notices',
    'Literature' => 'Literature',
  );
}

/**
 * Get the contributors.
 */
function trove_get_index_contributors() {
  $list = array();
  $result = db_query("SELECT nuc, name
    FROM {trove_contributors}");
  foreach ($result->fetchAllAssoc('nuc') as $arr) {
    $list[$arr->nuc] = $arr->name;
  }
  return $list;
}
